# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.(6,7,8)
python: 
  - "3.6"
  - "3.7"
  - "3.8"

# Install the codecov pip dependency
install:
  - pip install --upgrade pytest pytest-cov pytest-asyncio python3_anticaptcha

# Run the unit test
script:
  - pytest test.py --cov=./
